import type { VdsResult } from "./types/vds";

// API examples preserved verbatim; history metadata is added by the caller.
export const testResults: VdsResult[] = [
    {
        data: {
            destinataire: "ANTS",
            "durée de validité": { durée: 30, unité: "j" },
            "motif d'utilisation": "",
            "nom d'usage": "NOM D'USAGE",
            "nom de naissance": "MARTIN",
            prénoms: "Maëlis-Gaëlle Marie",
            sexe: "F",
            "date de naissance": "13/07/1990",
            "lieu de naissance": "PARIS",
            nationalité: "FRA",
        },
        header: {
            marqueurIdentification: "DE",
            version: "02",
            manifest_ID: "4A49",
            manifest_version: "02",
            certificate_reference: "FR05FIN2",
            sign_datetime: "2026-09-21 09:04:10",
            length: 74,
            "Type de document": {
                nomDuTypeDocument: {
                    en: "Identity Proof",
                    fr: "Justificatif d'identité",
                },
                descriptionDuTypeDocument: {
                    en: "Temporary Identity document",
                    fr: "Justificatif d'identité à usage unique",
                },
            },
        },
        signer: {
            cert_cn: "FIN2",
            cert_o: "Agence Nationale des Titres Sécurisés",
            cert_ou: "0002 130003262",
            cert_issuer: "FR05-test (ANTS)",
            cert_not_before: "Mon, 14 Sep 2026 12:27:07 GMT",
            cert_not_after: "Fri, 14 Sep 2029 12:27:07 GMT",
        },
        vds_standard: "DOC_105",
        testdata: false,
        sign_is_valid: true,
    },
    {
        data: {
            "Nombre de pages du document": "0001",
            "Liste des prénoms": ["DAVID"],
            "Date de naissance": "2000-06-03",
            "Lieu de naissance": "BELLEYDOUX",
            Nom: "GUY",
            Civilité: "MADAME",
            "N° Dossier": "170231164713",
            "Type de relevé de permis de conduire":
                "RIR - Relevé d'Information Restreint",
            "Etat du permis de conduire du conducteur": "SUSPENDU",
            "Date des données issues du SNPC": "2025-04-16 20:28",
            "Catégories présentes de permis de conduire": [""],
        },
        header: {
            "Date d’émission du document": "2025-04-16",
            "Date de création de la signature": "2025-04-16",
            "Identifiant de l’autorité de certification": "FR00",
            "Identifiant du certificat": "TES0",
            Version: "4",
            "Type de document": "Relevé d'Information Permis de conduire",
            Périmètre: "01",
            Pays: "FR",
        },
        signer: {
            cert_cn: "FIN2",
            cert_o: "Agence Nationale des Titres Sécurisés",
            cert_ou: "0002 130003262",
            cert_issuer: "FR05-test (ANTS)",
            cert_not_before: "Mon, 14 Sep 2026 12:27:07 GMT",
            cert_not_after: "Fri, 14 Sep 2029 12:27:07 GMT",
        },
        vds_standard: "DOC_101",
        testdata: false,
        sign_is_valid: true,
    },
    {
        data: {
            Prénom: "ANNE-SOPHIE",
            "Nom - ligne 1": "LEFEBVRE",
            "Nom - ligne 2": null,
            "Date de naissance": "1943-08-12",
            "Numéro de titre": "24GH00030",
            "Numéro de permis": "2024003455",
            "Date d'émission": "2024-07-12",
            "Option Côtière - Date d'effet": "1985-01-07",
            "Option Eaux Intérieures - Date d'effet": null,
            "Extension Grande Plaisance Eaux Intérieures - Date d'effet": null,
            "Extension Hauturière - Date d'effet": "1992-04-07",
            Options: null,
            Image_Portrait:
                "TsaJLCXefmjFcpH1spws1IxHz7/d0wXx7Wx+RTAr6lCOTBqHyQuij/kf1k61sSy33VYOgiV7YQGbRkzwY+CpUPHu0JFxjcsuGcW+As0fwEFWHX9wvnGj31CENwsfstN+RqyTsayT+ESfi3aVxweGFR2Kf7rTjyvSbck/T7mdprX0v71/oItEj+eSRdX4DU3Xeyosx5I2drIvhxcwkhngUGWz4DVVcKyc9D5Ay0NFPvpHfVB4J5oF2EJgXVqrrVdKdw6Bx10JTomQ7jHbE0Gh3w84KfwVb0mi3ivWpk1Ysunpxcunqmsh/iO/jw4x5+4b1uEgIGW1LLZEFUtgQhie5S2ypELEppy36FwbpXH8G/vaaG63LM3OD16NiqtXbnBJKmSFz7pCAtQmQxL+vZvpuwfWjP9EDasdNdDHW/J66gwkIY9fidxx1NV4GJ+PRhOa18DKphrF8gEOJHv3gxT6W4Jqx44rWrI3g0SwJUM7PFc/lxoVgDY04UXYmiSDuQ8uVH1lMPyZyYQRTytDZOyAMZxde11dKRj9yUQG4RmItLwokfvrHnPjbG3fNvhNrMOYKIpNv5h/CoGTWrnPc0kSt/6GEWfgtkCjhxfajxfWgJWVHadkwBaGVGPlW50EtqSkZk/ZonO93ouNzM0OaU9DFVpbM2Jw/QJaayLvhbdOppsbQQnhsUpVYIe51eF3I3+OqEkwPpRGaDK2pUtu2D7o5pVf/BijcGNyZRm2fv2ubmav9nshVXTIn9EV9K+HaTXcAuiH0GiqRO4Bu3Cq58ih8THKBk8LsWhhxY4UaNYJxljOAsv92OFvplJV5Cf1ULlGqKyxz9aGBiv3PJ98a4CweUSpQQunUVVSPxUsc85EQO7ZN7cPDwAhioGy4i6tSm5hHAzh3j5HP+FDchVKeK2EW5hhob9lIskS5Ez6qXW1NSNTK0S7KCp/exuYf8yfTYWjLEO6qFbwY7RFpUmXP5py5DhaIGWQ7ZhRKttUYoX+ivMmj22+aNk5m35nvpL6X9oUQDx3krx/XZOrZRGWZVtN5AbVA1wDT+t0VzTwI5UtNdq9Kb+eDIN5AFfltP4mOkvdN1eU9RqTTMBCXxibopEtbxlbuwRGggu0/3SdGk6tkOcSCzBbAEt/HFL4U6MxxJVeGFj2ZVsuSkmDLd1v1TIhQnCOu61ZB6+j/MmpER3SB4BqDICOpot4F6qRvcCmrrF4n8ZZgmigEoSejMosS/4/XpYxB4kl0QDlzXPUeixwx7Q=",
            CGU: "http://localhost/localhost12",
            Profil: "00",
        },
        header: {
            marqueurIdentification: "DE",
            version: "03",
            iac: "KFR",
            manifest_ID: "000406",
            certificate_reference: "FR000002",
            sign_datetime: "2026-03-05 13:39:40",
            length: 1037,
            "Type de document": {
                nomDuTypeDocument: {
                    fr: "Permis de Conduire - Bateaux de Plaisance à Moteur",
                },
                descriptionDuTypeDocument: {
                    fr: "Attestation de droits",
                },
            },
            cin: "MI",
            cf: "6",
        },
        signer: {
            cert_cn: "0002",
            cert_o: "SGIN",
            cert_ou: "SGIN",
            cert_issuer: "SGIN Test 2 (SGIN)",
            cert_not_before: "Fri, 09 Jan 2026 16:32:16 GMT",
            cert_not_after: "Mon, 07 Jan 2036 16:32:16 GMT",
        },
        vds_standard: "ISO 22376:2023",
        testdata: true,
        sign_is_valid: true,
    },
];
